# Generated by Django 5.0.7 on 2024-07-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocity',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='geostate',
            options={'ordering': ['name'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
    ]
